import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Especial Radio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cd.png" />
      </Head>
      <main className="bg-black font-serif text-yellow-50 w-screen h-screen flex items-center justify-center ">
        <div>Especial Radio</div>
      </main>
    </>
  );
}
